meta:
  environment: ~

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  serial: false

jobs:
  - name: gogs_z1
    templates:
    - name: gogs
      release: gogs
    - name: postgres
      release: gogs
    - name: nginx
      release: gogs
    instances: 0
    resource_pool: small_z1
    networks: (( merge ))
    persistent_disk: 0
    properties:
      networks:
        apps: gogs1


networks: (( merge ))

properties:
  gogs:
    port: 8080
  databases:
    db_scheme: postgres
    address: (( jobs.gogs_z1.networks.gogs1.static_ips.[0] ))
    port: 5524
    roles:
      - tag: gogs
        name: gogs
        password: gogs
    databases:
      - tag: gogs
        name: gogsdb
        citext: true
